### ISSUE TITLE
Small UI issues

### ISSUE THREAD

**Issue by whit1206** [dod-ccpo/atst#1137]
I deployed AT-AT locally on my mac and when logging in as Amanda and creating a portfolio, I noticed there was a few little UI bugs you may be aware of:

1. When selecting a dropdown the green checkmark appears, but if for whatever reason I move it back to "Select" it still appears checked. This also happens for groups of multi-select checkboxes. (It does work correctly for text fields when I remove text)
2. If I enter a dollar value into the CLIN Value field (TO setup) it does a pretty good job of keeping to a dollar amount, but it lets me keep "$123." and doesn't fix the display to "$123.00". It's minor but it looks weird. It also lets me type in "_" but when I navigate away it says its an invalid number. Can we just add that to the characters it's not allowed to enter? (both are minor)
3. Start date selection allows for months greater than 12 or days > 31. It will turn red while I'm typing, but turns back to blue for correct value when I tab out of it. If all fields are put in, it will correctly turn red, but not as I am typing them. It will allow an invalid month as 0 as the month, 1 as day if using a valid year (ex: 00 01 2020). It also allows day fields of 0 (but a separate check appears to be run when hitting next as a different kind of validation appears on the specific field, separate from the one done before).
4. I submitted a new TO and go to report and click on Manage TO and I get an "
jinja2.exceptions.UndefinedError: 'portfolio' is undefined" exception
5. Under adding a member under adding an application, for phone field, what if they have an international number, say on a Base or at a Legat or something where its not the standard 10 digit code?
6. There is no way to remove a member or revoke an invite.
7. It allows environments with no name to be added (just use spaces which are removed) and then if you edit one, it says the name is optional but it didn't say that when you create them.
8. Would it be possible to set the focus on the first text or UI item they have to fill out when they click on something like Add a new application?

**Comment by JRNPW** [comment]
Good morning, @whit1206! I'm putting these into Pivotal Tracker.

#2a: It was a conscious design decision not to reformat the amounts to include cents.

#2b: What browser and version are you using? I cannot input an underscore at all in Firefox, Safari, or Chrome on macOS Mojave.

#4: The Report screen is now an artifact from about three iterations ago of the TO system. It is undergoing redesign right now and will be updated very soon.

#5: This was a conscious decision during at least two planning sessions. The field is USA-formatted for MVP.

#6: "Revoke" is a bug that's underway right now. "Remove or delete" has been under design and dev review for at least one Sprint; it is also underway.

#8: This is being addressed with Bypass Blocks for Section 508 compliance. The options to skip the top nav and the side nav will be available in the near future.

**Comment by whit1206** [comment]
2a: If you are not reformatting the number to include cents, why do you allow them then? Do you plan to round if they are there or just allow it if its there? Would it be a good idea to indicate somehow with a whole number or say (rounded to the nearest dollar)?

2b: I am using Chrome version 77.0.3865.120 (Official Build) (64-bit), which is very latest as of a few days ago, in OSX Mojave 10.14.6. Just try typing a couple digits and then an underscore, or put the cursor mid number and hit it.

**Comment by JRNPW** [comment]
You'll need to take up the cents questions with the designers from Think Company. There are a few of them in the #at-at Slack channel.

I'm using the same version of Chrome. and I can't enter an underscore. I'm afraid that we can't replicate it.

**Comment by JRNPW** [comment]
@whit1206 We did our weekly Bug Triage this afternoon. All bugs were moved into the next Sprint except the ones about the validation checkmark. Even though they seem trivial, they will probably require some significant development. With the move into the integration phase, we've triaged them to stay in the Icebox as low-priority issues.

**Comment by JRNPW** [comment]
Resolving issue -- each item has been responded to or moved to Pivotal Tracker
