### ISSUE TITLE
Portfolio continue button displaying possible criteria instead of text

### ISSUE THREAD

**Issue by whit1206** [dod-ccpo/atst#1159]
When creating a new portfolio using the test user Amanda, the continue button shows what looks like testing criteria instead of continue text (see attached image).
<img width="253" alt="Screen Shot 2019-11-04 at 6 20 09 AM" src="https://user-images.githubusercontent.com/1154685/68127954-b7624e00-fecb-11e9-955a-09b8a45833ad.png">

**Comment by JRNPW** [comment]
Already captured as a bug card in Pivotal Tracker. The work is represented on PR #1153

**Comment by JRNPW** [comment]
@whit1206 The bugfix PR has been merged. The button's text is now correct on the site.
